run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - dupl
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - unused
    - staticcheck
    - errcheck

linters-settings:
  gofmt:
    simplify: true
  dupl:
    threshold: 400
