AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  learn-to-code-backend

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    ReservedConcurrentExecutions: 1 # Make sure no unexpected costs are created due to an error or unexpected external requests

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: (Required) Enter dev, prod. Default is dev.
    AllowedValues:
      - dev
      - prod

Resources:

  EventSourcingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StageName}_events"
      AttributeDefinitions:
        - AttributeName: aggregate_id
          AttributeType: S
        - AttributeName: version
          AttributeType: N
      KeySchema:
        - AttributeName: aggregate_id
          KeyType: HASH
        - AttributeName: version
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName

  ParticipantPost:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/post_participant
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: POST
            RestApiId: !Ref RestApi
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          ENVIRONMENT: !Sub "${StageName}"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${StageName}_events"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/hello/"
  ParticipantPost:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ParticipantPost.Arn
  ParticipantPostIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ParticipantPost.Arn
