GET https://dev.api.learn-to-code.io/courses/fcf7890f-9c72-46d3-931e-34494307be37
Next-Auth.Session-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2ViYXN0aWFuIFNpZ2wiLCJlbWFpbCI6ImFrcmlsbG84OUBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUVkRlRwNGRCbjEza3VMUWx3dnBKeFZ4R2JZdVpFMEVMc0hBS3RudmVlRE89czk2LWMiLCJzdWIiOiJjbGR2eXR3NmMwMDAwbDUwODZvZ3ZvdnI4IiwiaWF0IjoxNjc5MjUwOTQ5LCJleHAiOjE3ODE4NDI5NDl9.eruaZVelm8jW12PAFMREOw3vyFZQ098ZrfmtFGSuyhs
