GET https://dev.api.learn-to-code.io/participants/b4df3e8a-f2bd-4ed1-b723-12a48b72087c/quizzes/
Content-Type: application/json
Cookie: next-auth.session-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2ViYXN0aWFuIFNpZ2wiLCJlbWFpbCI6ImFrcmlsbG84OUBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jTGduenFHZnpRU3dZbXRtTHBMa3E5S0RXWjdubEF1UHF6c3d0TXZEcWN5PXM5Ni1jIiwic3ViIjoiYjRkZjNlOGEtZjJiZC00ZWQxLWI3MjMtMTJhNDhiNzIwODdjIiwiZXhwIjoxNzA2MDc4Njk3LCJpYXQiOjE3MDM0ODY2OTd9.o3CIHUJBAYtK1Dwq0M0mC43RYnP-gpqnFfZ92CQEAX4
