GET https://dev.api.learn-to-code.io/participants/87d91fb0-d87c-4ffd-bb80-42ab2e948c9d/quizzes/fcf7890f-9c72-46d3-931e-34494307be37/attempts/latest
Content-Type: application/json
Cookie: next-auth.callback-url=http%3A%2F%2Flocalhost%3A3000; next-auth.csrf-token=b801cc17759a69ba0ae23d2b4844bbbe7ac44ccf2bbe3a50b297c0fb6fd44207%7C6326f297c78970f1681464550f3ee0336cd9e4ceaabdddc277ec6f0869507725; next-auth.session-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2ViYXN0aWFuIFNpZ2wiLCJlbWFpbCI6ImFrcmlsbG84OUBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jTGduenFHZnpRU3dZbXRtTHBMa3E5S0RXWjdubEF1UHF6c3d0TXZEcWN5PXM5Ni1jIiwic3ViIjoiODdkOTFmYjAtZDg3Yy00ZmZkLWJiODAtNDJhYjJlOTQ4YzlkIiwiZXhwIjoxNzA1NTc1OTAzLCJpYXQiOjE3MDI5ODM5MDN9.-xoOLsml5DXgIrjjb_16imc1z-daM6wU3bOyyAKArdQ
