GET https://dev.api.learn-to-code.io/participants/87d91fb0-d87c-4ffd-bb80-42ab2e948c9d/quizzes/
Content-Type: application/json
Cookie: next-auth.session-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2ViYXN0aWFuIFNpZ2wiLCJlbWFpbCI6ImFrcmlsbG84OUBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUVkRlRwNGRCbjEza3VMUWx3dnBKeFZ4R2JZdVpFMEVMc0hBS3RudmVlRE89czk2LWMiLCJzdWIiOiJjbGR2eXR3NmMwMDAwbDUwODZvZ3ZvdnI4IiwiaWF0IjoxNjc5MjUwOTQ5LCJleHAiOjE3ODE4NDI5NDl9.eruaZVelm8jW12PAFMREOw3vyFZQ098ZrfmtFGSuyhs
